replicaCount: 3
image:
  tag: "81-4fde5971"
  repository: 539896451836.dkr.ecr.il-central-1.amazonaws.com/final-project
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
service:
  nodePort: 30082
