replicaCount: 4
image:
  tag: "81-4fde5971"
  repository: 539896451836.dkr.ecr.il-central-1.amazonaws.com/final-project
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
service:
  nodePort: 30083
