replicaCount: 2
image:
  tag: "81-4fde5971"
  repository: 539896451836.dkr.ecr.il-central-1.amazonaws.com/final-project
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
service:
  nodePort: 30081
